// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbbghhnblwffmlyyehyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiYmdoaG5ibHdmZm1seXllaHl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzE3NjgsImV4cCI6MjA3MDE0Nzc2OH0.8uU5lT4o_xNj3zABjCK1nLj-L1uLYEdQ3ufqkzYU6T0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});